selections:
- symbol: ICICIPRULI-LODHA
  strategy: PAIRS_MEANREV
  timeframe: 5
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 2.5
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 3394.347899999938
  score: 9.64537081578198
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 19638.149
    n_trades: 23
    win_rate: 73.913
    profit_per_trade: 853.8326
    avg_hold_min: 43.2609
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: BANKBARODA-TATACONSUM
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 789.403199999917
  score: 9.398072534783628
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 18092.8744
    n_trades: 7
    win_rate: 71.4286
    profit_per_trade: 2584.6963
    avg_hold_min: 120.0
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: NAUKRI-WIPRO
  strategy: PAIRS_MEANREV
  timeframe: 5
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 2.5
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 6810.450029999998
  score: 7.681573057614983
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 20219.187
    n_trades: 31
    win_rate: 61.2903
    profit_per_trade: 652.2318
    avg_hold_min: 51.2903
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: PNB-TATACONSUM
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 2460.191149999984
  score: 7.25927024380557
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 14700.8961
    n_trades: 11
    win_rate: 72.7273
    profit_per_trade: 1336.4451
    avg_hold_min: 69.5455
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: BHARTIARTL-LTIM
  strategy: PAIRS_MEANREV
  timeframe: 3
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 7156.784199999941
  score: 6.848985673161716
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 22709.8186
    n_trades: 59
    win_rate: 59.322
    profit_per_trade: 384.9122
    avg_hold_min: 29.1864
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: HCLTECH-SBILIFE
  strategy: PAIRS_MEANREV
  timeframe: 5
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 2.5
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 3650.0908999998883
  score: 6.5043020994497205
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 14980.6741
    n_trades: 34
    win_rate: 64.7059
    profit_per_trade: 440.6081
    avg_hold_min: 49.4118
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: BHARTIARTL-RELIANCE
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 1264.8426999999801
  score: 6.431921068866699
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 12460.9021
    n_trades: 8
    win_rate: 75.0
    profit_per_trade: 1557.6128
    avg_hold_min: 125.625
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: BANKBARODA-ULTRACEMCO
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 2123.7924999998922
  score: 6.389047826338913
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 13515.7436
    n_trades: 9
    win_rate: 66.6667
    profit_per_trade: 1501.7493
    avg_hold_min: 86.6667
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: SBILIFE-UNITDSPR
  strategy: PAIRS_MEANREV
  timeframe: 3
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 6402.649700000009
  score: 5.879417659783117
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 18301.8141
    n_trades: 56
    win_rate: 62.5
    profit_per_trade: 326.8181
    avg_hold_min: 31.3929
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: ETERNAL-SWIGGY
  strategy: PAIRS_MEANREV
  timeframe: 5
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 2.5
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 5570.207149999896
  score: 5.764633473440208
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 15975.3926
    n_trades: 32
    win_rate: 56.25
    profit_per_trade: 499.231
    avg_hold_min: 41.0938
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: CHOLAFIN-SBIN
  strategy: PAIRS_MEANREV
  timeframe: 3
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 6477.367499999842
  score: 5.4509780123455895
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 19553.4484
    n_trades: 66
    win_rate: 57.5758
    profit_per_trade: 296.2644
    avg_hold_min: 70.2273
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: ICICIGI-RELIANCE
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 498.0897999999788
  score: 5.270777627168037
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 11427.5432
    n_trades: 5
    win_rate: 60.0
    profit_per_trade: 2285.5086
    avg_hold_min: 162.0
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: ICICIGI-UNITDSPR
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 2771.772899999931
  score: 5.113483435237125
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 12676.1336
    n_trades: 14
    win_rate: 57.1429
    profit_per_trade: 905.4381
    avg_hold_min: 112.5
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: BHARTIARTL-ONGC
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 762.267749999963
  score: 4.914370124920582
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 8961.87
    n_trades: 8
    win_rate: 75.0
    profit_per_trade: 1120.2337
    avg_hold_min: 95.625
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: GAIL-INFY
  strategy: PAIRS_MEANREV
  timeframe: 3
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 11066.995179999783
  score: 4.720382837709868
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 19294.8861
    n_trades: 67
    win_rate: 59.7015
    profit_per_trade: 287.9834
    avg_hold_min: 28.7463
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: AMBUJACEM-BAJAJHFL
  strategy: PAIRS_MEANREV
  timeframe: 3
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 15109.122479999649
  score: 3.9852828863576093
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 20166.276
    n_trades: 72
    win_rate: 59.7222
    profit_per_trade: 280.0872
    avg_hold_min: 26.5833
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: SHREECEM-UNITDSPR
  strategy: PAIRS_MEANREV
  timeframe: 5
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 2.5
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 10010.85899999993
  score: 3.6147099080797576
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 15970.185
    n_trades: 47
    win_rate: 55.3191
    profit_per_trade: 339.7912
    avg_hold_min: 102.0213
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: ADANIENSOL-TRENT
  strategy: PAIRS_MEANREV
  timeframe: 5
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 2.5
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 6075.454650000062
  score: 3.0053725041447072
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 10207.7089
    n_trades: 38
    win_rate: 55.2632
    profit_per_trade: 268.6239
    avg_hold_min: 39.8684
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: ICICIGI-ONGC
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 1758.5963399999632
  score: 2.6789943011076804
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 6296.712
    n_trades: 6
    win_rate: 66.6667
    profit_per_trade: 1049.452
    avg_hold_min: 105.0
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: AXISBANK-CHOLAFIN
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 4764.577899999924
  score: 2.424727893904411
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 7789.574
    n_trades: 9
    win_rate: 66.6667
    profit_per_trade: 865.5082
    avg_hold_min: 78.3333
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: BPCL-UNITDSPR
  strategy: PAIRS_MEANREV
  timeframe: 5
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 2.5
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 4819.260849999835
  score: 2.383481524901787
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 7903.2411
    n_trades: 29
    win_rate: 58.6207
    profit_per_trade: 272.5256
    avg_hold_min: 55.1724
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: AMBUJACEM-TVSMOTOR
  strategy: PAIRS_MEANREV
  timeframe: 5
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.25
    stop_z: 2.5
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 5774.580999999973
  score: 2.35083399665443
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 7525.0095
    n_trades: 34
    win_rate: 61.7647
    profit_per_trade: 221.3238
    avg_hold_min: 51.6176
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: BPCL-ULTRACEMCO
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 1105.457949999875
  score: 1.204288310979146
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 2538.6102
    n_trades: 6
    win_rate: 66.6667
    profit_per_trade: 423.1017
    avg_hold_min: 45.0
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: ADANIPORTS-BEL
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 3637.619999999819
  score: 1.037940159358153
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 3983.8497
    n_trades: 6
    win_rate: 66.6667
    profit_per_trade: 663.975
    avg_hold_min: 35.0
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: BOSCHLTD-ULTRACEMCO
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 5591.7559999998975
  score: 0.6892053180294627
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 6124.325
    n_trades: 7
    win_rate: 57.1429
    profit_per_trade: 874.9036
    avg_hold_min: 94.2857
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
- symbol: CANBK-VEDL
  strategy: PAIRS_MEANREV
  timeframe: 15
  params:
    lookback: 120
    leverage: 5.0
    beta_lookback: 120
    entry_z: 2.0
    exit_z: 1.0
    stop_z: 3.0
    notional_per_leg: 50000.0
    base_notional: 100000.0
  max_dd: 7827.929449999997
  score: -1.569567644506034
  bucket: LOW
  risk_per_trade: 0.01
  stats:
    pnl: 3232.5661
    n_trades: 12
    win_rate: 58.3333
    profit_per_trade: 269.3805
    avg_hold_min: 83.75
  notional: 500000.0
  base_notional: 100000.0
  notional_per_leg: 50000.0
  leverage: 5.0
budgets:
  LOW: 0.4
  MED: 0.35
  HIGH: 0.25
reserve_frac: 0.2
