apiVersion: 1
datasources:
  - name: Trading Postgres
    uid: trading-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: trader
    secureJsonData:
      password: trader
    jsonData:
      database: trading
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
